apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: simple-akka-grpc-go-service
        image: 649414960431.dkr.ecr.eu-west-1.amazonaws.com/simple-grpc-go-service-access:latest
        ports:
        - containerPort: 8080
