apiVersion: v1
kind: Service
metadata:
  name: sample-grpc-server
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8090
